### ISSUE TITLE
在windows中编译无法通过

### ISSUE THREAD

**Issue by kardusenor** [SXKDZ/homework-template#1]
我用的vscode+latex-workshop编译hw.tex无法编译通过，且没有报错提示，不知道大佬用的什么编译环境

**Comment by SXKDZ** [comment]
中文的需要XeLaTeX，英文的应该用pdfLaTeX就行

**Comment by kardusenor** [comment]
可以发邮件交换联系方式私聊吗，我感觉是我的本地latex环境配置问题，网上也找不到解决方案。
hw.tex在overleaf上编译通过了
